services:

# T-Pot Init Service
  tpotinit:
    build: .
    container_name: tpotinit
    env_file:
      - $HOME/Honeypot/.env
    restart: "no"
    stop_grace_period: 60s
    image: "dtagdevsec/tpotinit:24.04"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/Honeypot/data:/data
    network_mode: "host"
    cap_add:
     - NET_ADMIN
