networks:
  heralding_local:

services:

# Heralding service
  heralding:
    build: .
    container_name: heralding
    restart: always
    tmpfs:
     - /tmp/heralding:uid=2000,gid=2000
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - heralding_local
    ports:
     - "2120:21"
     - "2222:22"
     - "2323:23"
     - "2525:25"
     - "8000:80"
     - "1100:110"
     - "1430:143"
     - "8443:443"
     - "465:465"
     - "993:993"
     - "995:995"
     - "1080:1080"
     - "3306:3306"
     - "3389:3389"
     - "5432:5432"
     - "5900:590"
    image: "dtagdevsec/heralding:24.04"
    read_only: true
    volumes:
     - $HOME/tpotce/data/heralding/log:/var/log/heralding
